### ISSUE TITLE
PHP Fatal error:  Class 'Kohana_Kostache' not found in pplication/classes/kostache.php on line 24

### ISSUE THREAD

**Issue by ghost** [system76/beansbooks#201]
Greetings I would like to use BeansBooks as the foundation of a accounting back end for another project. BeansBooks works fine on a test server using PHP 5.3.27 and we felt confident enough to start evaluating earnestly so installed on our dev server which is running PHP 5.3.3 which immediately threw this error in apache log: "PHP Fatal error:  Class 'Kohana_Kostache' not found in 
/var/www/accounting/html/application/classes/kostache.php on line 24"  and this error to the Browser: "A fatal error has occurred: 
Kohana_Exception [ 0 ]: The requested route does not exist: 
exception ~ SYSPATH/classes/kohana/route.php [ 106 ]"

Anyone know what might be wrong and how to correct it?
Is there any additional information that I need to provide?

Thanks, Richard Newman, Pittsburgh PA USA

**Comment by stratus-ss** [comment]
I am having the exact same problem. My steps to reproduce this are:

1) spin up Ubuntu 14.04
2) Install required modules as per https://github.com/system76/beansbooks (and setup apache2/ssl)
3) cd /var/www/html
4) git clone --recursive https://github.com/system76/beansbooks.git
5) create the htaccess file
6) change the ownerships according to the above link
7) visit my local beansbooks (https://beansbooks)

I have tried your git submodule command but that didnt change anything. Additionally I wiped the directory and started the git clone again with the same affect

**Comment by funnylookinhat** [comment]
I'm having trouble replicating the issue...

Could you run the following command and paste the result? `ls -lht /var/www/html/`

**Comment by stratus-ss** [comment]
```
root@accounting:/var/www/html# ls -lht /var/www/html/                                            
total 2.0K
drwxr-xr-x 8 root root 17 Feb 22 09:00 beansbooks
root@accounting:/var/www/html# ls -lht /var/www/html/beansbooks/
total 53K
drwxr-xr-x 11 root root   12 Feb 22 08:57 system
drwxr-xr-x  5 root root    5 Feb 22 08:57 static
drwxr-xr-x  6 root root    6 Feb 22 08:57 modules
drwxr-xr-x  2 root root    3 Feb 22 08:57 install_files
-rw-r--r--  1 root root 3.3K Feb 22 08:57 index.php
-rw-r--r--  1 root root  809 Feb 22 08:57 example.htaccess
drwxr-xr-x  8 root root    9 Feb 22 08:57 application
-rw-r--r--  1 root root  542 Feb 22 08:57 TESTS.md
-rw-r--r--  1 root root 8.8K Feb 22 08:57 README.md
-rw-r--r--  1 root root 1.7K Feb 22 08:57 KOHANA.LICENSE.md
-rw-r--r--  1 root root  11K Feb 22 08:57 BEANSBOOKS.LICENSE.md
-rw-r--r--  1 root root  11K Feb 22 08:57 BEANSBOOKS.CONTRIBUTING.md
```

Here is my beansbook.conf in case that is relevent

```
<IfModule mod_ssl.c>
	<VirtualHost _default_:443>
		ServerAdmin webmaster@localhost
                ServerName beansbooks 
                ServerAlias beansbooks 

                DocumentRoot /var/www/html/beansbooks            
               <Directory /var/www/html/beansbooks>
                    Options FollowSymLinks
                    AllowOverride All
                    Require all granted
               </Directory>
		
		ErrorLog ${APACHE_LOG_DIR}/error.log
		CustomLog ${APACHE_LOG_DIR}/access.log combined

		SSLEngine on

		SSLCertificateFile	/etc/apache2/ssl/apache.crt
		SSLCertificateKeyFile /etc/apache2/ssl/apache.key

		<FilesMatch "\.(cgi|shtml|phtml|php)$">
				SSLOptions +StdEnvVars
		</FilesMatch>
		<Directory /usr/lib/cgi-bin>
				SSLOptions +StdEnvVars
		</Directory>

		BrowserMatch "MSIE [2-6]" \
				nokeepalive ssl-unclean-shutdown \
				downgrade-1.0 force-response-1.0
		BrowserMatch "MSIE [17-9]" ssl-unclean-shutdown

	</VirtualHost>
</IfModule>
```

**Comment by membiblio** [comment]
David,

     Remember I had this same issue and you said that some files were 
missing in my installation. I had used git on the linux host and, 
somehow, it did not check everything out. I used a git client on my 
windows machine to dl locally then used ftp to sent it up to the linux 
host, changed owndership and permissions appropriately (following your 
installation guide) and it worked automagically.

     I hope this helps. I could zip up my working directory and let you 
dl it as a zip file if that would work.

     Also my copy has the extra code that lets someone use 1.5 for 
quantity/hours where previously you enforced 1/2/3 only. I gave up 
trying to figure out how to contribute this back. If someone can give me 
a step by step to create a patch I would be happy to do that as well - 
then email you my result to be contributed.


Richard Newman
Pittsburgh Embedworx
Pittsburgh PA USA
412.452.8472 voice / text ok

**Comment by stratus-ss** [comment]
Richard,

Thanks for the information. Based on what you said, I did the git clone on my Arch Linux box, blew away the directory on Ubuntu and then rsync'd it over.

After changing the permissions via the readme (including the htaccess) I can now continue with the install.

For reference here is the ```du -c *``` from both machines. There is definitely a difference

Ubuntu: ```17216	total```
Arch: ```20560	total```

**Comment by stratus-ss** [comment]
Ubuntu listing: http://pastebin.com/gvRpmwYn
Arch Listing: http://pastebin.com/2QGunfam

Hopefully this is helpful

**Comment by funnylookinhat** [comment]
@stratus-ss Thanks for the file listings!  Glad you got it figured out.

We're eventually going to migrate away from sub-modules and replace them with Composer ( https://getcomposer.org/ ) - that should fix this in the long run.  The strange part is that this issue ONLY seems to happen when people want to put BeansBooks in their /var/www/html directory, not anywhere else...  leads me to believe it's a permissions issue or something.

When you did the `git clone` command were you running it as root?  Or as a user?

**Comment by stratus-ss** [comment]
@funnylookinhat on the Ubuntu box I did the git clone as root, initially in the /root directory and then moved it over to /var/www/html. The second time on Ubuntu (also as root) I did the git clone directly into the /var/www/html directory (after deleting the initial folder)

On Arch I did the clone as a regular user in my home directory and rsync'd it over

**Comment by funnylookinhat** [comment]
Hmm - must have something to do with permissions then - because the kostache files were definitely in each.  Thanks for doing the legwork - that certainly helps narrow these things down.  :)
