### ISSUE TITLE
Mcrypt

### ISSUE THREAD

**Issue by kc135pirate** [system76/beansbooks#222]
Really looking forward to giving beansbook a run. The problem is that I followed the install guide to a T and I still can not set it up. I keep getting a Missing Mcrypt support or Rjindael-128 notice when starting the installation process. Mcrypt version is 2.6.8 and libmcypt is 2.5.8. I am trying to set this up on ubuntu server 64-bit 14.04.1. 

Thanks for your help,

Travis

**Comment by funnylookinhat** [comment]
Hey Travis -

What's the output of running this command? `$ php -r 'echo print_r(mcrypt_list_algorithms(),TRUE);'`

Also - have you installed the `php5-mcrypt` package?

**Comment by kc135pirate** [comment]
travis@ubuntu:~$ php -r 'echo print_r(mcrypt_list_algorithms(),TRUE);'
PHP Fatal error:  Call to undefined function mcrypt_list_algorithms() in Command line code on line 1

php5-mcrypt was the current version

**Comment by funnylookinhat** [comment]
Hmm - sounds like mcrypt isn't installed correctly for PHP - if it was, you would get a list of supported algos.

Try running these lines again:

```
sudo apt-get update
sudo apt-get install apache2 php5 libapache2-mod-php5 php5-cli php5-mysql php5-mcrypt php5-gd mysql-server mysql-client git  
```

If that doesn't work, you'll have to try to manually enable the mcrypt module with php.

**Comment by funnylookinhat** [comment]
@kc135pirate Did you get it working?  You might have to run the following in a terminal to manually enable the mcrypt extensions.

```
sudo php5enmod mcrypt
```

**Comment by kc135pirate** [comment]
That did the trick. Thanks!
