### ISSUE TITLE
*Unofficial* BeansBooks API for PHP (version 1.0.0)

### ISSUE THREAD

**Issue by cdp1337** [system76/beansbooks#230]
https://github.com/eVAL-Agency/BeansBooksAPI

It's a little rough at present, but we have a working library with many of the objects and actions implemented.  Contributing the code back to the community in upholding the spirit of FOSS. :)

**Comment by funnylookinhat** [comment]
This is awesome!  Thanks for sharing.

**Comment by funnylookinhat** [comment]
Going to make a note of this in the README.md
