### ISSUE TITLE
Accounts listed in $ when currency set to £

### ISSUE THREAD

**Issue by edwbaker** [system76/beansbooks#231]
My currency is set to £ (GBP), but the /accounts page still lists the account values in USD.

**Comment by funnylookinhat** [comment]
This should be a pretty easy fix.  Are there any other pages you've noticed that have the same issue?  I'd like to take care of them all at once.

**Comment by edwbaker** [comment]
Not that I can see. I had a quick look through the reports and there's some inconsistency in that some use the currency symbol for figures, and some don't. Bit all those that do use the correct one.

**Comment by funnylookinhat** [comment]
Got it.  Thanks for reporting - we'll make sure this is fixed in the next dev sprint.

**Comment by funnylookinhat** [comment]
Fixed in development branch (v1.4rc1).  Will be released with v1.4.
