### ISSUE TITLE
Expenses Report - Empty

### ISSUE THREAD

**Issue by funnylookinhat** [system76/beansbooks#249]
If the dash expenses report returns no information it should show a message rather than a blank chart.

**Comment by WatchMkr** [comment]
I think we show the previous month until there is data for the current month. When months switch over, I regularly look at the previous one ( especially since it doesn't have all the data until it's end of month anyway.

**Comment by funnylookinhat** [comment]
Right - but I also thought of the use case whereby you just created a fresh instance, so there wouldn't be any data to show at all.  In that case, we'd just show a message I think.

**Comment by WatchMkr** [comment]
Yes, good point.

**Comment by funnylookinhat** [comment]
At what point would it make sense for us to show aggregate data for the last N months?  i.e. if this month AND last month both didn't have data, but we could get a good report with averages over the last 6 months, would that be better to show than simply "Sorry, no data?"

I think it would - but trying to figure out the best use cases for each feels like blowing the scope out of proportion.

The other two reports on that page default to YTD and the last 12 months.  I wonder if it would be more useful to show something like that by default instead of just the last month?  Or does that make it too hard to spot a trend?

**Comment by WatchMkr** [comment]
Let's keep it simple. Data from the previous month that has data. "Enter Operating Expenses to Generate the Report" otherwise.
