### ISSUE TITLE
Leaving pages results in loss of data entry

### ISSUE THREAD

**Issue by mattsys76** [system76/beansbooks#253]
Problem: Actions such as clicking 'back' in the browser allows the leaving of pages  ../vendors/payments and ../customers/payments thereby resulting in the unintentional loss of data that was entered on the page.

A dialog box confirming that the user does indeed wish to leave the page first should eliminate the unintended consequences.

**Comment by funnylookinhat** [comment]
This seems to work when creating Sales Orders / Expenses / Purchase Orders - going to test and verify that Payments is implemented the same.
