### ISSUE TITLE
Incompatibility with PHP7 or broken Kohanan?

### ISSUE THREAD

**Issue by chthonik** [system76/beansbooks#272]
Installed BB and the page that is loaded appears to be broken.  There are hyperlinks to "Dash", "Customers", etc., but the links yield a 404.  There are no apache errors, but the access log shows that the .js files are being `fetched.`  

`- [19/Jan/2018:21:51:15 -0500] "GET /static/js/libs/select2.3.2.2.min.js HTTP/1.1" 404 527
- [19/Jan/2018:21:51:15 -0500] "GET /static/js/script.js?v=1.5.2 HTTP/1.1" 404 511 "http:/
- [19/Jan/2018:21:51:15 -0500] "GET /static/js/interface.js?v=1.5.2 HTTP/1.1" 404 514 "htt
- [19/Jan/2018:21:51:15 -0500] "GET /static/js/dash.js?v=1.5.2 HTTP/1.1" 404 509 "http://1
- [19/Jan/2018:21:51:15 -0500] "GET /static/js/accounts.js?v=1.5.2 HTTP/1.1" 404 513 "http
- [19/Jan/2018:21:51:15 -0500] "GET /static/js/customers.js?v=1.5.2 HTTP/1.1" 404 514 "htt
- [19/Jan/2018:21:51:15 -0500] "GET /static/js/vendors.js?v=1.5.2 HTTP/1.1" 404 512 "http:
- [19/Jan/2018:21:51:15 -0500] "GET /static/js/setup.js?v=1.5.2 HTTP/1.1" 404 510 "http://
- [19/Jan/2018:21:51:15 -0500] "GET /static/js/auth.js?v=1.5.2 HTTP/1.1" 404 509 "http://1
- [19/Jan/2018:21:51:15 -0500] "GET /static/js/myaccount.js?v=1.5.2 HTTP/1.1" 404 514 "htt
- [19/Jan/2018:21:53:01 -0500] "GET /accounts/ HTTP/1.1" 404 502 
- [19/Jan/2018:21:53:05 -0500] "GET /html/beansbooks/ HTTP/1.1" 404 5963 "http://1
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/ubuntu-webfont/ubuntu-webfont.css HTTP/1.1
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/jqueryui/jquery-ui-1.8.22.custom.css HTTP/
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/select2/select2.3.2.2.css HTTP/1.1" 404 52
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/h5bp.css HTTP/1.1" 404 512 "http://
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/main.css?v=1.5.2 HTTP/1.1" 404 512 "http:/
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/accounts.css?v=1.5.2 HTTP/1.1" 404 515 "ht
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/customers.css?v=1.5.2 HTTP/1.1" 404 516 "h
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/dash.css?v=1.5.2 HTTP/1.1" 404 511 "http:/
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/form.css?v=1.5.2 HTTP/1.1" 404 511 "http:/
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/vendors.css?v=1.5.2 HTTP/1.1" 404 515 "htt
- [19/Jan/2018:21:53:05 -0500] "GET /static/css/setup.css?v=1.5.2 HTTP/1.1" 404 513 "http:
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/jquery-ui-1.8.24.min.js HTTP/1.1" 404
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/jquery-1.7.2.min.js HTTP/1.1" 404 526
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/chart.min.js HTTP/1.1" 404 519 "http:/
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/jquery.modaldialog.js HTTP/1.1" 404 52
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/spin.min.js HTTP/1.1" 404 518 "http://
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/jquery.spin.js HTTP/1.1" 404 521 "http
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/jquery.ezpz_hint.js HTTP/1.1" 404 526
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/json2.js HTTP/1.1" 404 515 "http://
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/select2.3.2.2.min.js HTTP/1.1" 404 527
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/interface.js?v=1.5.2 HTTP/1.1" 404 514 "htt
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/dash.js?v=1.5.2 HTTP/1.1" 404 509 "http://1
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/accounts.js?v=1.5.2 HTTP/1.1" 404 513 "http
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/customers.js?v=1.5.2 HTTP/1.1" 404 514 "htt
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/script.js?v=1.5.2 HTTP/1.1" 404 511 "http:/
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/vendors.js?v=1.5.2 HTTP/1.1" 404 512 "http:
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/setup.js?v=1.5.2 HTTP/1.1" 404 510 "http://
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/myaccount.js?v=1.5.2 HTTP/1.1" 404 514 "htt
- [19/Jan/2018:21:53:05 -0500] "GET /static/images/logo.png HTTP/1.1" 404 514 "http://
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/auth.js?v=1.5.2 HTTP/1.1" 404 509 "http://1
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/jquery-ui-1.8.24.min.js HTTP/1.1" 404
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/chart.min.js HTTP/1.1" 404 519 "http:/
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/spin.min.js HTTP/1.1" 404 518 "http://
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/jquery.modaldialog.js HTTP/1.1" 404 52
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/jquery.spin.js HTTP/1.1" 404 521 "http
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/jquery.ezpz_hint.js HTTP/1.1" 404 526
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/json2.js HTTP/1.1" 404 515 "http://
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/libs/select2.3.2.2.min.js HTTP/1.1" 404 527
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/script.js?v=1.5.2 HTTP/1.1" 404 511 "http:/
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/interface.js?v=1.5.2 HTTP/1.1" 404 514 "htt
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/dash.js?v=1.5.2 HTTP/1.1" 404 509 "http://1
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/accounts.js?v=1.5.2 HTTP/1.1" 404 513 "http
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/customers.js?v=1.5.2 HTTP/1.1" 404 514 "htt
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/vendors.js?v=1.5.2 HTTP/1.1" 404 512 "http:
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/setup.js?v=1.5.2 HTTP/1.1" 404 510 "http://
- [19/Jan/2018:21:53:05 -0500] "GET /static/js/auth.js?v=1.5.2 HTTP/1.1" 404 509 "http://1
- [19/Jan/2018:21:53:06 -0500] "GET /static/js/myaccount.js?v=1.5.2 HTTP/1.1" 404 514 "htt
19/Jan/2018:21:53:11 -0500] "OPTIONS * HTTP/1.0" 200 126 "-" "Apache/2.4.18 (Ubuntu) (inte
:/var/www/html$`

`

    Dash
    Customers
    Vendors
    Accounts
    Setup

404 Error
The requested URL html/beansbooks was not found on this server.

BeansBooks Version 1.5.2
 
 
 

Please wait...

 `

**Comment by bencates** [comment]
The version of Kohana used in BeansBooks does **not** support PHP 7. We require a version of PHP 5 >= 5.3. The readme has been updated to reflect this.
